#!/usr/bin/env bash

scriptdir="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")" )" >/dev/null && pwd )"
bindir="$(cd "${scriptdir}/../../bin" >/dev/null && pwd )"

# Create a git repository
mkdir gitab
cd gitab
git init
mkdir a
mkdir b

git config user.name "compogit test"
git config user.email test@compogit.com

# Add compogit configuration
cp -r "${scriptdir}/compogit" ./
git add .
git commit -m "Add compogit configuration"

# Switch to a development branch --# and set some weird user name
git checkout -b dev
# git config user.name "private compogit test"
# git config user.email privatetest@compogit.com

# Create commits which don't touch multiple components.
echo a1 > a/a.txt
echo b1 > b/b.txt
git add a/a.txt
git commit -m "Initial commit to a/a.txt"
git add b/b.txt
git commit -m "Initial commit to b/b.txt"

# Create a commit which touches two components.
echo a2 > a/a.txt
echo b2 > b/b.txt
git add .
git commit -m "Commit to both components"

# Only modify a.txt
echo a3 > a/a.txt
git add a/a.txt
git commit -m "Modify a/a.txt"

# Only modify b.txt
echo b4 > b/b.txt
git add b/b.txt
git commit -m "Modify b/b.txt"

# Get a log ...
echo "Before split:"
git log --format=format:"%h %s%n"

# Split the unpushed commits
${bindir}/compogit-split-all-unpushed-commits

# Get a log ...
echo "After split:"
git log --format=format:"%h %s%n"

# Switch back to master --# and set the original user name
git checkout master
# git config user.name "compogit test"
# git config user.email test@compogit.com

# get the output of git cherry
git cherry HEAD dev -v

# get commits to component A from branch dev which still need to be merged.
${bindir}/compogit-cherry-component + A HEAD dev

# cherry pick the commits to A
${bindir}/compogit-cherry-pick-component A HEAD dev

# Get a log ...
echo "After cherry-picking A:"
git log --format=format:"%h %s%n"
echo "After cherry-picking A (cherry):"
git cherry HEAD dev -v

# cherry pick the commits to B
${bindir}/compogit-cherry-pick-component B HEAD dev --pick -x

# Get a log ...
echo "After cherry-picking B:"
git log
echo "END OF LOG"
echo "After cherry-picking B (cherry):"
git cherry HEAD dev -v

# Count the occurrences of "cherry picked from commit"
pickmsgcount=$(git log --format=format:%s%n%b%n | grep "cherry picked from commit" | wc -l)

# Check whether the commits are as expected.
git log --format=format:%s%n  > logmessages.txt
echo "" >> logmessages.txt

diff -u "${scriptdir}/expected.txt" logmessages.txt > logmessages.diff

status="FAIL"
cmp --silent "${scriptdir}/expected.txt" logmessages.txt \
	&& [ "$(git status --branch --porcelain | head -n 1)" == "## master" ] \
	&& [ "$pickmsgcount" == 3 ] \
	&& status="ok"
echo $status >> "../status.txt"
