#!/usr/bin/env bash

scriptdir="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")" )" >/dev/null && pwd )"
bindir="$(cd "${scriptdir}/../../bin" >/dev/null && pwd )"

synopsis_line=$(${bindir}/compogit-ann-components-to-filelist-given-compospec 2>&1 < /dev/null | grep USAGE)
if [ "${synopsis_line}" == "USAGE" ]; then
	echo "ok" >> status.txt
else
	echo "FAILED" >> status.txt
fi
