#!/usr/bin/env bash

scriptdir="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")" )" >/dev/null && pwd )"
bindir="$(cd "${scriptdir}/../../bin" >/dev/null && pwd )"

#pycall="${pycovercall} ${bindir}/compogit-get-component-from-compospec.py ${scriptdir}/compospec.json"

${bindir}/compogit-get-component-from-compospec "${scriptdir}/compospec.json" 2>./call.stderr.txt < "${scriptdir}/filelist.txt"
if grep -q AmbiCompo ./call.stderr.txt; then
	echo "ok" >> status.txt
else
	echo "FAILED" >> status.txt
fi
